version: '3.0'

services:
  frontend:
    image: todororoff318/testfr:testfr
    container_name: frontend
    ports:
      - "8888:8888"
    depends_on:
      - backend

  backend:
    image: todororoff318/test:test
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:


